Expose fdd version as metric
fiaas/fiaas-deploy-daemon pull request #152
Opened 2021-04-28 08:21 UTC by ninaangelvik

2021-04-28 08:56 UTC, mortenlj commented on fiaas_deploy_daemon/deployer/version_exporter.py
> +        self.version_gauge.labels(app_spec.name, app_spec.version).set(1)
This will create a metric with the name and version of the deployed apps as labels, not the version of FDD that is running.

2021-04-28 09:18 UTC, oyvindio requested changes
It looks like the `deployer_fdd_version` metric here effectively tracks `app_spec.version` (i.e. the version field in fiaas.yml) of the most recently deployed application. To solve #143 it might make sense to use `config.version`, which should contain the image tag for the running fiaas-deploy-daemon docker image (via the VERSION or FIAAS_VERSION env variables). This could simplify the implementation too; it might make sense to put all of it in [`Main`](https://github.com/fiaas/fiaas-deploy-daemon/blob/master/fiaas_deploy_daemon/__init__.py#L84).

2021-04-28 09:18 UTC, oyvindio commented on fiaas_deploy_daemon/deployer/version_exporter.py
> +    version_gauge = Gauge("deployer_fdd_version", "Current FDD version",["app_name", "version"])
Maybe [Info](https://github.com/prometheus/client_python/#info) is a more suitable metric type for static information such as a version number ?

2021-04-30 07:39 UTC, jamesmcdonald commented
/sem-approve

2021-04-30 08:17 UTC, oyvindio commented
/sem-approve

2021-05-04 07:53 UTC, oyvindio approved these changes

2021-05-04 07:59 UTC, merged