split out ingress into beta and stable
fiaas/fiaas-deploy-daemon pull request #165
Opened 2021-11-26 13:13 UTC by j18e

With Kubernetes 1.22 on the way and the removal of beta api's for ingresses impending, it's time to implement the possibility for using stable ingresses in fiaas. The models for these have already been implemented in the k8s library. This PR should, when finished, provide a feature flag to operators which tells FDD to use the stable ingresses. Otherwise beta ingresses will be used.

2021-11-29 13:36 UTC, j18e commented
we are holding off on this until a new version of the k8s library is released, one that includes both stable ingress and stable CRD.

2021-11-30 14:13 UTC, oyvindio reviewed
I think this mostly looks good, but it would be ideal to have tests for the ingress adapter classes as well as how they are used in the ingress module.
 I've left a few questions and suggestions in line as well

2021-12-13 12:24 UTC, j18e commented on fiaas_deploy_daemon/config.py
> +                            action="store_true", default=False)
good point. fixed.

2021-12-13 12:40 UTC, j18e commented on fiaas_deploy_daemon/deployer/kubernetes/ingress.py
>              pass
sounds good

2022-01-14 15:01 UTC, oyvindio requested changes
I think this looks quite good. 👍  For completeness sake, I think it would be very nice to include the v1 ingress feature in the e2e test (especially as v1beta1 ingress support would be removed at some point in the future). In addition I've left a few comments in line regarding a few minor issues

2022-02-02 07:40 UTC, oyvindio submitted a review, later dismissed
LGTM 👍

2022-02-02 09:28 UTC, oyvindio approved these changes

2022-02-02 09:30 UTC, merged