avoid using get_or_create for updating serviceAccounts
fiaas/fiaas-deploy-daemon pull request #173
Opened 2022-03-01 11:28 UTC by j18e

re https://github.com/fiaas/fiaas-deploy-daemon/issues/172

2022-03-01 11:44 UTC, tg90nor commented on fiaas_deploy_daemon/deployer/kubernetes/service_account.py
> +            service_account = ServiceAccount.get_or_create(
You don't need `get_or_create` here. This can simply be written as `ServiceAccount(metadata=...)`

2022-03-01 12:12 UTC, tg90nor approved these changes
LGTM

2022-03-01 12:15 UTC, tg90nor commented
The two get requests for the app service account can be combined to avoid one api call, but I'm fine with this either way

2022-03-02 16:00 UTC, oyvindio requested changes
This approach seems reasonable, but there are a few minor issues I think it would be nice to address before merging; see comments in line

2022-03-03 07:29 UTC, j18e commented on fiaas_deploy_daemon/deployer/kubernetes/service_account.py
> +        service_account.metadata = metadata
good catch

2022-03-07 12:36 UTC, oyvindio approved these changes
LGTM 👍

2022-03-07 13:13 UTC, merged